### ISSUE TITLE
crashing when hit by warg

### ISSUE THREAD

**Issue by sladejoker** [Lycanite/LycanitesMobs#105]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/10/15 4:24 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 318
	Entity Name: Slam
	Entity's Exact location: 319.95, 95.62, 46.38
	Entity's Block location: World: (319,95,46), Chunk: (at 15,5,14 in 19,2; contains blocks 304,0,32 to 319,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.38, 0.40, 0.47
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

**Comment by Lycanite** [comment]
This is likely caused by another mod messing up the potion effects, because there is no api for potions provided by forge, all mods have to wrestle to get their potion effects working, Lycanites Mobs has a friendly technique that tries it's best to work with other mods, however it's very easy for any mod to just clear the list and force only it's own potion effects in thus breaking every other mod, unfortunately I can;t do much about this.

There are two things you can do, track down the mod causing this and report that bug to the author or you can open up the lycanitesmobs-general.cfg config file, find the Potion Effects category, and set "Enable Custom Effects" to false, this will disable all custom effects and will also disable the Warg's paralysis ability. You can also try giving each effect a custom ID (try setting them to something like 50 counting upwards), though this all depends on what the other mod has done to the potion effects list.

**Comment by sladejoker** [comment]
Ahh okay thanks for the reply! Really appreciate how hard you work on this mod!

**Comment by Lycanite** [comment]
No probs and thanks! I'm glad to hear you enjoy the mod! :D

**Comment by sladejoker** [comment]
It turns out I don't have any more available potion ids.. any way to increase the amount?

**Comment by Lycanite** [comment]
The list can be increased to anything but IDs over 128 cause weird problems for some unknown vanilla-related reason.
