### ISSUE TITLE
Crash While Opening

### ISSUE THREAD

**Issue by OnurMeteCandar** [Lycanite/LycanitesMobs#119]
I have the latest version of the mod and when it finishes loadin the mobs the game crashes.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11.09.2015 21:34
Description: Initializing game

net.minecraftforge.client.model.ModelFormatException: IO Exception reading model format
	at net.minecraftforge.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:60)
	at net.minecraftforge.client.model.obj.ObjModelLoader.loadInstance(ObjModelLoader.java:27)
	at net.minecraftforge.client.model.AdvancedModelLoader.loadModel(AdvancedModelLoader.java:65)
	at lycanite.lycanitesmobs.AssetManager.addObjModel(AssetManager.java:66)
	at lycanite.lycanitesmobs.AssetManager.getObjModel(AssetManager.java:123)
	at lycanite.lycanitesmobs.infernomobs.model.ModelCinder.<init>(ModelCinder.java:25)
	at lycanite.lycanitesmobs.infernomobs.model.ModelCinder.<init>(ModelCinder.java:20)
	at lycanite.lycanitesmobs.infernomobs.ClientSubProxy.registerModels(ClientSubProxy.java:20)
	at lycanite.lycanitesmobs.infernomobs.InfernoMobs.preInit(InfernoMobs.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: ınfernomobs:models/entity/cinder.obj
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:71)
	at net.minecraftforge.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:55)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:60)
	at net.minecraftforge.client.model.obj.ObjModelLoader.loadInstance(ObjModelLoader.java:27)
	at net.minecraftforge.client.model.AdvancedModelLoader.loadModel(AdvancedModelLoader.java:65)
	at lycanite.lycanitesmobs.AssetManager.addObjModel(AssetManager.java:66)
	at lycanite.lycanitesmobs.AssetManager.getObjModel(AssetManager.java:123)
	at lycanite.lycanitesmobs.infernomobs.model.ModelCinder.<init>(ModelCinder.java:25)
	at lycanite.lycanitesmobs.infernomobs.model.ModelCinder.<init>(ModelCinder.java:20)
	at lycanite.lycanitesmobs.infernomobs.ClientSubProxy.registerModels(ClientSubProxy.java:20)
	at lycanite.lycanitesmobs.infernomobs.InfernoMobs.preInit(InfernoMobs.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 105335368 bytes (100 MB) / 212512768 bytes (202 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	lycanitesmobs{1.11.0.6 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	arcticmobs{1.11.0.6 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	demonmobs{1.11.0.6 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	desertmobs{1.11.0.6 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	forestmobs{1.11.0.6 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	freshwatermobs{1.11.0.6 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCE	infernomobs{1.11.0.6 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	junglemobs{1.11.0.6 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	mountainmobs{1.11.0.6 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	plainsmobs{1.11.0.6 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	saltwatermobs{1.11.0.6 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	shadowmobs{1.11.0.6 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	swampmobs{1.11.0.6 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.11.0.6 [1.7.10].jar) 
	UCH	bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2869' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.2869, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 2.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by OnurMeteCandar** [comment]
Can anyone help

**Comment by Lycanite** [comment]
Looks like a bad download as it's failing to read/find a model file, I'd try downloading again.

If you're in a development environment and are modding with Lycanites Mobs I'd try running:
gradlew clean --refresh-dependencies
gradlew setupDecompWorkSpace
