### ISSUE TITLE
Certain Effects cause Client Side Crash

### ISSUE THREAD

**Issue by O13SC3N3** [Lycanite/LycanitesMobs#138]
1.7.10 Minecraft. Forget 1556

Not all mobs do it. I noticed the Barghest? and the Geonach has crashed completely out of the game. Yet server remains with no error.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 1/24/16 11:41 AM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: -128
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1132)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1132)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: plainsmobs.ventoraptor (lycanite.lycanitesmobs.plainsmobs.entity.EntityVentoraptor)
	Entity ID: 1175176
	Entity Name: Ventoraptor
	Entity's Exact location: 1273.94, 87.00, 293.84
	Entity's Block location: World: (1273,87,293), Chunk: (at 9,5,5 in 79,18; contains blocks 1264,0,288 to 1279,255,303), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.07, -0.08, -0.02
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-

**Comment by Lycanite** [comment]
Ah this looks like a conflict with potion IDs, do you have any other mods that add custom potion effects, as they might be messing up the id list?
You can change all potion effects from Lycanites mobs or assign custom potion ids via the config if needed.
Come Minecraft 1.9, potion effect IDs will be automatic like block and item IDs are now, but until then, it's really tricky.

**Comment by O13SC3N3** [comment]
Yeah I figured out if I turn off mob special effects, it worked. potion ids were all unique. And your wonderful mobs still had their nasty effects. Only other issue I have seems spawn rates regardless what I enter. But either way its fun!

**Comment by Lycanite** [comment]
I'm glad to hear it's working!
What are your spawning issues?

**Comment by O13SC3N3** [comment]
Its forge :p lol. Increased spawns, dies out, to many, to few, restarts seem to fix it. Its just a flat forge server, so not much choice for plugins. Otherwise its cool. I find it amusing SpecialAI works with your passive mobs... People walk by a Maka just to get Spearheaded from behind by it.

**Comment by Lycanite** [comment]
Lol yeah I tried to make mod mod as compatible with other mods as I can, thus SpecialAI!

**Comment by O13SC3N3** [comment]
Any plans on adding them MOB To do list on your main site? Or you switching hard to 1.8.9 like many of them?

**Comment by Lycanite** [comment]
I've been looking at 1.8.9, I've recently discovered the like of Smart block models which means no JSON files will be necessary which was the main roadblock for me, but I might wait it out until 1.9 too, we shall see

**Comment by O13SC3N3** [comment]
Well wish you luck and again Thanks for the great mod. My player base hates me with the other mods I tied in with yours... Creep factor pretty evil ;p

**Comment by Lycanite** [comment]
Lol nice, what's Minecraft without a bit of terror!
