### ISSUE TITLE
Crashes with ClassNotFoundException

### ISSUE THREAD

**Issue by cyanobacterium** [Lycanite/LycanitesMobs#156]
Hi Lycanite. I love this mod!

However, I got a strange crash while I was playing in my test world. It appears to be looking for the class com.sun.javafx.geom.Vec2d and not finding it for some reason. I'm running Java 8 so I'm rather surprised that this class isn't in my classpath when running Minecraft (and yes, I triple-checked the profile editor to confirm that the correct version of Java is being used).
Here's the stacktrace (and crash report file):

java.lang.NoClassDefFoundError: com/sun/javafx/geom/Vec2d
	at lycanite.lycanitesmobs.plainsmobs.entity.EntityRoc.func_70636_d(EntityRoc.java:109)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1249)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.geom.Vec2d
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
[crash-2016-06-12_20.57.29-server.txt](https://github.com/Lycanite/LycanitesMobs/files/311071/crash-2016-06-12_20.57.29-server.txt)

**Comment by Lycanite** [comment]
Lycanites Mobs 1.14.3.0 has this issue, upgrading to the latest 1.14.3.2 should fix this. :)
