### ISSUE TITLE
1.9.4 Error with Darkling on LycanitesMobsComplete 1.14.3.2 

### ISSUE THREAD

**Issue by DarcClan** [Lycanite/LycanitesMobs#158]
Below is the error log, this is the client error, server stays up, same error every time I log in with that mob around

```
--- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/19/16 4:47 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.getLatchTarget(EntityDarkling.java:173)
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.hasLatchTarget(EntityDarkling.java:205)
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.func_70636_d(EntityDarkling.java:130)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:385)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1249)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1788)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.getLatchTarget(EntityDarkling.java:173)
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.hasLatchTarget(EntityDarkling.java:205)
	at lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling.func_70636_d(EntityDarkling.java:130)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:385)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1249)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
	Entity Type: shadowmobs.darkling (lycanite.lycanitesmobs.shadowmobs.entity.EntityDarkling)
	Entity ID: 15840
	Entity Name: Darkling
	Entity's Exact location: -228.53, 41.00, 192.47
	Entity's Block location: World: (-229,41,192), Chunk: (at 11,2,0 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Darc_Clan'/15818, l='MpServer', x=-188.71, y=67.00, z=216.35]]
	Chunk stats: MultiplayerChunkCache: 185, 185
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10499 game time, 10499 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityEnderman['Enderman'/15872, l='MpServer', x=-129.50, y=17.00, z=146.50], EntityArix['Arix'/15873, l='MpServer', x=-129.52, y=44.00, z=224.48], EntityItem['item.tile.sapling.big_oak'/15874, l='MpServer', x=-129.66, y=72.00, z=239.13], EntitySheep['Sheep'/15875, l='MpServer', x=-131.50, y=66.00, z=266.50], EntityPlayerSP['Darc_Clan'/15818, l='MpServer', x=-188.71, y=67.00, z=216.35], EntitySheep['Sheep'/15876, l='MpServer', x=-133.50, y=66.00, z=267.50], EntitySheep['Sheep'/15877, l='MpServer', x=-139.27, y=71.00, z=262.50], EntitySheep['Sheep'/15878, l='MpServer', x=-130.74, y=66.00, z=272.46], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15879, l='MpServer', x=-132.80, y=68.25, z=284.77], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15880, l='MpServer', x=-142.12, y=70.32, z=287.96], EntityKobold['Kobold'/15881, l='MpServer', x=-127.30, y=34.00, z=155.48], EntityKobold['Kobold'/16009, l='MpServer', x=-174.50, y=15.00, z=216.50], EntityEnderman['Enderman'/15882, l='MpServer', x=-122.50, y=25.00, z=171.50], EntityEnderman['Enderman'/15883, l='MpServer', x=-114.50, y=33.00, z=251.50], EntityBat['Bat'/15884, l='MpServer', x=-117.05, y=34.86, z=250.18], EntityBat['Bat'/15885, l='MpServer', x=-118.25, y=55.10, z=253.25], EntityBat['Bat'/15889, l='MpServer', x=-259.92, y=34.68, z=143.66], EntityCreeper['Creeper'/16145, l='MpServer', x=-259.50, y=45.00, z=200.50], EntitySheep['Sheep'/15890, l='MpServer', x=-265.50, y=69.00, z=143.50], EntitySheep['Sheep'/15891, l='MpServer', x=-268.34, y=68.00, z=143.91], EntityKobold['Kobold'/16154, l='MpServer', x=-121.50, y=25.00, z=172.50], EntityZombie['Zombie'/15916, l='MpServer', x=-261.48, y=21.33, z=200.24], EntityCreeper['Creeper'/15917, l='MpServer', x=-263.50, y=28.00, z=197.50], EntityCryptZombie['Crypt Zombie'/15923, l='MpServer', x=-267.75, y=34.00, z=164.25], EntityMakaAlpha['Maka Alpha'/15941, l='MpServer', x=-262.12, y=66.33, z=188.70], EntityMakaAlpha['Maka Alpha'/15942, l='MpServer', x=-258.69, y=68.00, z=188.95], EntityKobold['Kobold'/15943, l='MpServer', x=-101.25, y=36.00, z=153.50], EntityKobold['Kobold'/15944, l='MpServer', x=-106.81, y=38.00, z=157.19], EntityEnderman['Enderman'/15819, l='MpServer', x=-186.50, y=23.00, z=209.50], EntityVillager['Villager'/15820, l='MpServer', x=-186.27, y=67.00, z=219.50], EntityZombie['Zombie'/15821, l='MpServer', x=-249.50, y=65.00, z=147.50], EntityEnderman['Enderman'/15949, l='MpServer', x=-109.50, y=21.00, z=178.50], EntityItem['item.item.seeds'/15822, l='MpServer', x=-247.43, y=66.00, z=170.13], EntityCreeper['Creeper'/15823, l='MpServer', x=-252.50, y=20.00, z=185.50], EntityChupacabra['Chupacabra'/15824, l='MpServer', x=-242.51, y=22.00, z=179.49], EntityZombie['Zombie'/15825, l='MpServer', x=-247.50, y=42.00, z=194.50], EntityCreeper['Creeper'/15826, l='MpServer', x=-249.19, y=47.33, z=200.29], EntityZombie['Zombie'/15827, l='MpServer', x=-252.50, y=41.00, z=193.50], EntitySheep['Sheep'/15828, l='MpServer', x=-244.78, y=63.00, z=198.49], EntitySheep['Sheep'/15829, l='MpServer', x=-252.00, y=68.00, z=196.64], EntityShambler['Shambler'/15957, l='MpServer', x=-149.56, y=18.00, z=307.44], EntitySheep['Sheep'/15830, l='MpServer', x=-250.50, y=67.00, z=196.50], EntitySheep['Sheep'/15831, l='MpServer', x=-252.94, y=68.00, z=196.24], EntitySheep['Sheep'/15832, l='MpServer', x=-249.50, y=68.00, z=214.50], EntitySheep['Sheep'/15833, l='MpServer', x=-247.95, y=68.67, z=216.61], EntitySheep['Sheep'/15834, l='MpServer', x=-245.60, y=67.00, z=213.64], EntitySheep['Sheep'/15835, l='MpServer', x=-248.33, y=68.00, z=212.37], EntityItem['item.item.seeds'/15836, l='MpServer', x=-247.54, y=63.00, z=251.13], EntitySkeleton['Skeleton'/15837, l='MpServer', x=-224.50, y=35.00, z=172.50], EntitySkeleton['Skeleton'/15838, l='MpServer', x=-237.50, y=45.00, z=180.50], EntityChupacabra['Chupacabra'/15839, l='MpServer', x=-229.49, y=45.00, z=176.51], EntityEnderman['Enderman'/15967, l='MpServer', x=-110.50, y=33.00, z=283.50], EntityDarkling['Darkling'/15840, l='MpServer', x=-228.53, y=41.00, z=192.47], EntitySquid['Squid'/15841, l='MpServer', x=-230.17, y=56.54, z=228.60], EntityItem['item.item.seeds'/15842, l='MpServer', x=-232.25, y=62.00, z=233.88], EntityGrue['Grue'/15843, l='MpServer', x=-233.63, y=14.00, z=260.63], EntityVillager['Villager'/15844, l='MpServer', x=-214.50, y=69.00, z=208.50], EntityItem['item.tile.sapling.oak'/15845, l='MpServer', x=-216.13, y=63.00, z=246.88], EntityVillager['Villager'/15846, l='MpServer', x=-200.50, y=74.00, z=221.39], EntityVillager['Villager'/15847, l='MpServer', x=-206.28, y=70.00, z=218.46], EntityVillager['Villager'/15848, l='MpServer', x=-206.50, y=70.00, z=216.50], EntityVillager['Villager'/15849, l='MpServer', x=-202.47, y=71.00, z=209.51], EntityItem['item.tile.flower1.dandelion'/15850, l='MpServer', x=-204.13, y=73.00, z=213.41], EntityItem['item.tile.cloth.black'/15851, l='MpServer', x=-193.70, y=69.00, z=216.76], EntityVillager['Villager'/15852, l='MpServer', x=-193.53, y=70.00, z=217.77], EntityVillager['Villager'/15853, l='MpServer', x=-201.61, y=73.77, z=218.51], EntityVillager['Villager'/15854, l='MpServer', x=-192.20, y=74.00, z=227.32], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15855, l='MpServer', x=-192.78, y=65.04, z=275.61], EntityItem['item.item.seeds'/15856, l='MpServer', x=-188.99, y=75.00, z=243.69], EntityBat['Bat'/15857, l='MpServer', x=-187.40, y=17.92, z=278.01], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15858, l='MpServer', x=-185.45, y=69.43, z=273.71], EntityArisaur['Arisaur'/15859, l='MpServer', x=-174.32, y=64.00, z=208.02], EntityKobold['Kobold'/15860, l='MpServer', x=-168.52, y=24.00, z=218.48], EntityKobold['Kobold'/15861, l='MpServer', x=-173.53, y=23.00, z=234.47], EntityZoataur['Zoataur'/15862, l='MpServer', x=-173.69, y=48.00, z=230.31], EntityEnderman['Enderman'/15863, l='MpServer', x=-165.50, y=53.00, z=251.54], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15864, l='MpServer', x=-175.93, y=70.54, z=283.67], EntityAfrit['Afrit'/15865, l='MpServer', x=-144.76, y=37.82, z=217.93], EntityCephignis['Cephignis'/15866, l='MpServer', x=-148.56, y=42.00, z=214.44], EntityCephignis['Cephignis'/15867, l='MpServer', x=-148.59, y=38.00, z=214.41], EntityCephignis['Cephignis'/15868, l='MpServer', x=-148.53, y=41.00, z=214.47], VengeanceSpirit['Vengeance Spirit'/15869, l='MpServer', x=-149.10, y=37.00, z=211.59], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15870, l='MpServer', x=-150.49, y=75.86, z=270.08], EntityButterfly['entity.BiomesOPlenty.butterfly.name'/15871, l='MpServer', x=-149.38, y=74.91, z=275.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:490)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1966738480 bytes (1875 MB) / 4268163072 bytes (4070 MB) up to 4268163072 bytes (4070 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M -XX:MaxPermSize=516M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
	FML: MCP 9.28 Powered by Forge 12.17.0.1965 Optifine OptiFine_1.9.4_HD_U_B6 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1965.jar) 
	UCHIJA	Forge{12.17.0.1965} [Minecraft Forge] (forge-1.9.4-12.17.0.1965.jar) 
	UCHIJA	cei{1.2} [Chunk Edge Indicator] (1.9.4-chunkedgeindicator-1.2.jar) 
	UCHIJA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJA	BiomesOPlenty{4.1.0.2026} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2026-universal.jar) 
	UCHIJA	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCHIJA	BloodMagic{1.9.4-2.0.1-44} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-44.jar) 
	UCHIJA	bookshelf{1.2.3.275} [Bookshelf] (Bookshelf-1.9.4-1.2.3.275.jar) 
	UCHIJA	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UCHIJA	lootablebodies{2.1.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies_1.9.4-2.1.0.jar) 
	UCHIJA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UCHIJA	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.9.4-3.0.0.43_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.43_alpha.jar) 
	UCHIJA	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UCHIJA	FFS{1.9.4-1.6.1-b20} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.1-b20.jar) 
	UCHIJA	forestry{5.0.18.165} [Forestry] (forestry_1.9.4-5.0.18.165.jar) 
	UCHIJA	IronChest{6.0.145.787} [Iron Chest] (ironchest-1.9.4-6.0.145.787.jar) 
	UCHIJA	journeymap{1.9.4-5.2.3} [JourneyMap] (journeymap-1.9.4-5.2.3-unlimited.jar) 
	UCHIJA	jeresources{0.4.6.37} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.37.jar) 
	UCHIJA	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCHIJA	lycanitesmobs{1.14.3.2 - MC 1.9.4} [Lycanites Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	arcticmobs{1.14.3.2 - MC 1.9.4} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	demonmobs{1.14.3.2 - MC 1.9.4} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	desertmobs{1.14.3.2 - MC 1.9.4} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	forestmobs{1.14.3.2 - MC 1.9.4} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	freshwatermobs{1.14.3.2 - MC 1.9.4} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	infernomobs{1.14.3.2 - MC 1.9.4} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	junglemobs{1.14.3.2 - MC 1.9.4} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	mountainmobs{1.14.3.2 - MC 1.9.4} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	plainsmobs{1.14.3.2 - MC 1.9.4} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	saltwatermobs{1.14.3.2 - MC 1.9.4} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	shadowmobs{1.14.3.2 - MC 1.9.4} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	swampmobs{1.14.3.2 - MC 1.9.4} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.3.2 [1.9.4].jar) 
	UCHIJA	Morpheus{1.9.4-3.1.5} [Morpheus] (Morpheus-1.9.4-3.1.5.jar) 
	UCHIJA	RealisticTorches{1.5.6} [Realistic Torches] (RealisticTorches-1.9.4-1.5.6.jar) 
	UCHIJA	rftools{4.62} [RFTools] (rftools-1.9.4-4.62.jar) 
	UCHIJA	rftoolsdim{4.30beta42} [RFTools Dimensions] (rftoolsdim-1.9.4-4.30beta42.jar) 
	UCHIJA	Roguelike{1.5.2} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.2.jar) 
	UCHIJA	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UCHIJA	saoui{1.9-1.6.0-Dev1} [Sword Art Online UI] (saoui-1.9.4-1.6.0-Dev1.jar) 
	UCHIJA	Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar) 
	UCHIJA	torcherino{1.9.4-2.4.0} [Torcherino] (Torcherino-TehNut-1.9.4-2.4.0.jar) 
	UCHIJA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.192.jar) 
	UCHIJA	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.192.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX TITAN X/PCIe/SSE2'
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Launched Version: 1.9.4-forge1.9.4-12.17.0.1965
	LWJGL: 2.9.4
	OpenGL: GeForce GTX TITAN X/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.22, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: BDcraft Musics Pack (incompatible), BDcraft Sounds Pack (incompatible), PureBDcraft  64x MC19
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@58ee7337
	OptiFine Version: OptiFine_1.9.4_HD_U_B6
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.08 Extreme.zip
	OpenGlVersion: 4.5.0 NVIDIA 368.22
	OpenGlRenderer: GeForce GTX TITAN X/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Lycanite** [comment]
That's strange, it looks like the data manager is being messed up and is sending the wrong type of data from server to client. How does your server run, is it launched through any wrappers like mark2?
I'll run some tests myself.

**Comment by Lycanite** [comment]
With a standard forge client and server I can't replicate the crash, I did get a lot of problems like this when launching my server through the mark2 wrapper, so it could be something along those lines.

**Comment by DarcClan** [comment]
I'm not sure, I'm using the hosting service Creeperhost though.

**Comment by Lycanite** [comment]
It might be CreeperHost then but I'll keep looking into it. Does it happen 100% of the time?

**Comment by DarcClan** [comment]
I'm not sure because before this error I can't say i've seen a darkling before running around, is their a console command in vanilla minecraft server to delete mobs? I mean i can try using a spawn egg, but I don't want to lock myself out of my server. I guess I could back the server up and try.

**Comment by DarcClan** [comment]
OK tried in single player and it worked fine spawning one in, and on the server I reluctantly spawned one and it worked. Unfortunately I'm still afraid of having that error happening and since that error kept crashing the client, I think its safer to keep them from spawning till its determined how/why this error occured

**Comment by DarcClan** [comment]
Also as a secondary thing I've noticed its incredably hard to herd Maka, they almost always refuse to jump one block high step-ups, even using a lead

**Comment by WhiteFire-Sondergaard** [comment]
I also got this error running a forge server, no wrapper. Ended up having to pull the mod.

**Comment by WhiteFire-Sondergaard** [comment]
Actually found that I could just disable that one mob and it deleted the one that was causing problems, so woot for that at least. :)

**Comment by Lycanite** [comment]
I'm releasing a (probably final) 1.9.4 build 1.14.3.3 which will add a catch for this error which means it should just stop the crash but Darklings may sometimes clip out of plae for a second or so.

**Comment by APolarBaer** [comment]
im getting this error too even after i removed your mod though...

**Comment by Lycanite** [comment]
Hmm if it's after then it looks like there could be interference from server wrappers or perhaps it could be a vanilla or forge bug too.

**Comment by APolarBaer** [comment]
how would i check for a wrapper, because it doesnt happen in singleplayer and im using a hosting service:/

**Comment by Lycanite** [comment]
Hosting services usually have admin controls which are kind of wrappers themselves so it could be the admin controls breaking things, it could also be a Forge or Vanilla issue, but if this happens with a vanilla server i'd say it was the hosting service's admin controls.

**Comment by Lycanite** [comment]
For my modded server which has no issues, I pay ~$40 per month for a decent virtual server with 4GB RAM, 256GB SSD and 2 CPU cores, it runs Ubuntu Server where I have minecraft forge running with my mods as well as my Lycanites Mobs website and database which stores player familiars too!

**Comment by APolarBaer** [comment]
i cant really spare 40, if its in USD id end up paying like 52 a month, thats too much forme >w<

**Comment by Lycanite** [comment]
Yeah but you can get a lower spec server, it depends what you get from your Minecraft-only service instead really, I prefer a full server for my websites, etc too but it's not the best option for everyone.

**Comment by APolarBaer** [comment]
https://premium.bisecthosting.com

**Comment by Lycanite** [comment]
Wow those are some decent prices! I like to do a lot more with my server than just Minecraft though but for Minecraft alone it looks like a good deal. I'd ask them about that error though and see what they say about it.

**Comment by APolarBaer** [comment]
ive tried dropping down to forge forge-1.9.4-12.17.0.1980-1.10.0 instead of 1987 and it seems to have been what it is.. even though now the servers running 1980 and the clients are all 1987

**Comment by APolarBaer** [comment]
ill come back if it happens again and its not the wrapper lol...

**Comment by APolarBaer** [comment]
26.06 19:28:24 [Server] INFO net.minecraft.util.ReportedException: Ticking player
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[ls.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) ~[mc.class:?]
26.06 19:28:24 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[em.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mb.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
26.06 19:28:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
26.06 19:28:24 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
26.06 19:28:24 [Server] INFO at com.inventorypets.petAnvil.func_77663_a(petAnvil.java:310) ~[petAnvil.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:435) ~[adq.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:340) ~[zi.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:498) ~[zj.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976) ~[sa.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:227) ~[zj.class:?]
26.06 19:28:24 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[ls.class:?]
26.06 19:28:24 [Server] INFO ... 9 more
26.06 19:28:24 [Disconnect] User APolarBaer has disconnected, reason: Internal server error .......
one thing to another >w<

**Comment by APolarBaer** [comment]
alright so the forge change didnt work, still crashed from it again

**Comment by Lycanite** [comment]
Damn that's annoying! XD That last log looks like InvetoryPets might be the cause. Clients and Servers don't need the exact same version and the problem is with the server sending the wrong information to the client causing a client side crashed triggered by the server. Or maybe it's the clients mapping up the data sent by the server incorrectly.

**Comment by APolarBaer** [comment]
yeah it is inventory pets, ive added it to https://github.com/capnkirok/Inventory-Pets/issues/89

i just wish i could find this enderman thing >w<
