### ISSUE TITLE
LycanitesMobsComplete 1.15.1.2 [1.10.2]

### ISSUE THREAD

**Issue by ktole1999** [Lycanite/LycanitesMobs#175]
tried with previous version and same error.

forge-1.10.2-12.18.1.2052. launching from Curse as well as vanilla launcher. Tried using 3gb and 4gb and no change.

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at net.minecraft.util.ResourceLocation.toString(SourceFile:51)
	at net.minecraftforge.client.model.ModelLoader$DefaultTextureGetter.apply(ModelLoader.java:1143)
	at net.minecraftforge.client.model.ModelLoader$DefaultTextureGetter.apply(ModelLoader.java:1137)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:125)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:538)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Lycanite** [comment]
Ah so this is a problem with the Java Garbage Collector, there are some
settings you can use to change how the GC works. Which version of Java are
you using, as I think Java 8 deals with the GC differently, if you are
using 8 then a setting may need to be changed, when I get to my home PC
I'll be able to copy over the settings I use for you.
