### ISSUE TITLE
Casting Bug (Belph)

### ISSUE THREAD

**Issue by dotModded** [Lycanite/LycanitesMobs#187]
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
    at lycanite.lycanitesmobs.demonmobs.entity.EntityBelph.func_70636_d(EntityBelph.java:119)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at lycanite.lycanitesmobs.core.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1250)
    at net.minecraft.world.World.redirect$onCallEntityUpdate$zjk000(World.java:1044)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1211)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by xlxAciDxlx** [comment]
Related to #183, Lycanite's working on a fix for these types of crashes.

**Comment by Lycanite** [comment]
Yup same casting bug, I'll have a fix coming in the next update. :D

**Comment by Lycanite** [comment]
Going to close duplicate casting issues, I may have a solution for this coming in the next update 1.15.1.5! :D
