### ISSUE TITLE
1.12.2 Lycanites issue or not... 

### ISSUE THREAD

**Issue by MadRatSRP** [Lycanite/LycanitesMobs#268]
Sorry for disturbing, but have u ever seen this issue in minecraft? I dont know how to find wrong mod... I cant say for sure is it from Lycanites or not but maybe you may help me with advice, if u want.
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
![ml](https://user-images.githubusercontent.com/29717217/33244457-8c8c3498-d308-11e7-94e9-8ac00ee790c5.png)

**Comment by Lycanite** [comment]
Hmm, it looks like it could have crashed from anywhere, could you send the full crash log please?

**Comment by MadRatSRP** [comment]
[crash-2017-11-27_00.12.33-server.txt](https://github.com/Lycanite/LycanitesMobs/files/1506401/crash-2017-11-27_00.12.33-server.txt)
yes, here it is

**Comment by MadRatSRP** [comment]
It seems that issue comes from the FoamFix or Ecology, am i right?

**Comment by Lycanite** [comment]
Yeah looks like FoamFix.
