### ISSUE TITLE
IE and Scorchfire Crash (seems to be same as #184?)

### ISSUE THREAD

**Issue by orcdash** [Lycanite/LycanitesMobs#300]
An Afrit tossed scorchfire onto an IE LV connector and the world crashed,  The error message is pretty well identical to the #184 shadowfire error so I'm guessing the fix is the same. Might want to check anything else you have inheriting from BlockFireBase as well

Description: Exception while updating neighbours

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class blusunrize.immersiveengineering.common.blocks.metal.BlockTypes_Connector, values=[CONNECTOR_LV, RELAY_LV, CONNECTOR_MV, RELAY_MV, CONNECTOR_HV, RELAY_HV, CONNECTOR_STRUCTURAL, TRANSFORMER, TRANSFORMER_HV, BREAKERSWITCH, REDSTONE_BREAKER, ENERGY_METER, CONNECTOR_REDSTONE, CONNECTOR_PROBE]} as it does not exist in BlockStateContainer{block=infernomobs:scorchfire, properties=[age, east, north, south, up, west]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockConnector.isSideSolid(BlockConnector.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:802)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:519)
	at com.lycanitesmobs.core.block.BlockFireBase.func_189540_a(BlockFireBase.java:228)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.world.World.func_175722_b(World.java:439)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.world.World.func_175656_a(World.java:424)
	at com.lycanitesmobs.infernomobs.entity.EntityScorchfireball.placeBlock(EntityScorchfireball.java:111)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70184_a(EntityProjectileBase.java:284)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at com.lycanitesmobs.core.entity.EntityProjectileBase.func_70071_h_(EntityProjectileBase.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Lycanite** [comment]
I've added a try catch for this in the upcoming 1.17.4.4 build, should ensure no mod conflict crashes.
