### ISSUE TITLE
This time it's Shadowfire. Is this related to the previously fixed Doomfire bug?

### ISSUE THREAD

**Issue by luckyp3616** [Lycanite/LycanitesMobs#345]
BTW, it was a Baby Skeleton from Mekanism that collided with the fire.

java.lang.NullPointerException: Colliding entity with block
	at net.minecraft.entity.EntityLivingBase.func_70687_e(EntityLivingBase.java:760)
	at com.lycanitesmobs.shadowmobs.block.BlockShadowfire.func_180634_a(BlockShadowfire.java:96)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.AbstractSkeleton.func_70636_d(SourceFile:139)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Lycanite** [comment]
Ah yes I can see how this has happened, easy fix, will be patched next update.

**Comment by Lycanite** [comment]
Will be fixed next update: https://github.com/Lycanite/LycanitesMobs/commit/5b36baa7c7f73d0d5bb91903aeedb4893a7a7c93

**Comment by luckyp3616** [comment]
This time I was able to work around it, thankfully, so it isn't urgent for me.

**Comment by Lycanite** [comment]
Ah good!
Well this fix is applied and will be included in the next update!
