### ISSUE TITLE
crashing 1.12.2 and 1.12

### ISSUE THREAD

**Issue by iplayminecraf** [Lycanite/LycanitesMobs#346]
when ever i launch minecarft and load up a world lags few mins later it crashes i need a fix mods: lycanites mobs. and crashes ill give the crash report       ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/20/18 9:41 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(Lnet/minecraft/entity/EntityLiving;Lnet/minecraft/world/World;FFFZ)Lnet/minecraftforge/fml/common/eventhandler/Event$Result;
	at com.lycanitesmobs.core.spawner.Spawner.doSpawn(Spawner.java:457)
	at com.lycanitesmobs.core.spawner.Spawner.trigger(Spawner.java:333)
	at com.lycanitesmobs.core.spawner.trigger.SpawnTrigger.trigger(SpawnTrigger.java:122)
	at com.lycanitesmobs.core.spawner.trigger.TickSpawnTrigger.onTick(TickSpawnTrigger.java:91)
	at com.lycanitesmobs.core.spawner.SpawnerEventListener.onEntityUpdate(SpawnerEventListener.java:180)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_SpawnerEventListener_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:544)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2080)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.lycanitesmobs.core.spawner.Spawner.doSpawn(Spawner.java:457)
	at com.lycanitesmobs.core.spawner.Spawner.trigger(Spawner.java:333)
	at com.lycanitesmobs.core.spawner.trigger.SpawnTrigger.trigger(SpawnTrigger.java:122)
	at com.lycanitesmobs.core.spawner.trigger.TickSpawnTrigger.onTick(TickSpawnTrigger.java:91)
	at com.lycanitesmobs.core.spawner.SpawnerEventListener.onEntityUpdate(SpawnerEventListener.java:180)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_SpawnerEventListener_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:544)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2080)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 0
	Entity Name: xSqeree_
	Entity's Exact location: -77.50, 64.00, -773.50
	Entity's Block location: World: (-78,64,-774), Chunk: (at 2,4,10 in -5,-49; contains blocks -80,0,-784 to -65,255,-769), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@58c385b3
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 229266352 bytes (218 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCHIJAAAA	lycanitesmobs{1.19.1.2 - MC 1.12.2} [Lycanites Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	arcticmobs{1.19.1.2 - MC 1.12.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	demonmobs{1.19.1.2 - MC 1.12.2} [Lycanites Demon Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	desertmobs{1.19.1.2 - MC 1.12.2} [Lycanites Desert Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	elementalmobs{1.19.1.2 - MC 1.12.2} [Lycanites Elemental Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	forestmobs{1.19.1.2 - MC 1.12.2} [Lycanites Forest Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	freshwatermobs{1.19.1.2 - MC 1.12.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	infernomobs{1.19.1.2 - MC 1.12.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	junglemobs{1.19.1.2 - MC 1.12.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	mountainmobs{1.19.1.2 - MC 1.12.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	plainsmobs{1.19.1.2 - MC 1.12.2} [Lycanites Plains Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	saltwatermobs{1.19.1.2 - MC 1.12.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	shadowmobs{1.19.1.2 - MC 1.12.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	UCHIJAAAA	swampmobs{1.19.1.2 - MC 1.12.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete+1.19.1.2+[1.12.2].jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['xSqeree_'/0, l='New World', x=-77.50, y=64.00, z=-773.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Lycanite** [comment]
Ah it looks like the forge event in 1.12 and 1.12.2 is different in some way to 1.12.2, I'll have to mark Lycanites Mobs as unstable for Minecraft 1.12 and 1.12.1.
To fix the issue, update to 1.12.2 as I don't currently have enough time support older versions.
You could also try Lycanites Mobs 1.17.1.3 which should work on 1.12. and 1.12.1.

**Comment by iplayminecraf** [comment]
really appreciate  this thanks  for the help BTW Great mod i have seen mod reviews and they are amazing looking forward to this mod!!!!

**Comment by Lycanite** [comment]
Thanks! :D
