### ISSUE TITLE
[Targeting] NPE Client Side PvP Check

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#395]
Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.func_72939_s(World.java:1770) ~[amu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.func_184191_r(EntityCreatureTameable.java:361) ~[EntityCreatureTameable.class:?]
	at com.lycanitesmobs.core.entity.EntityCreatureBase.canAttackEntity(EntityCreatureBase.java:2350) ~[EntityCreatureBase.class:?]
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.canAttackEntity(EntityCreatureTameable.java:428) ~[EntityCreatureTameable.class:?]
	at com.lycanitesmobs.freshwatermobs.entity.EntityAbaia.func_70636_d(EntityAbaia.java:121) ~[EntityAbaia.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377) ~[vq.class:?]
	at com.lycanitesmobs.core.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1370) ~[EntityCreatureBase.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	... 10 more
[23:57:25] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (backpacks+1.12.2+-+3.4.4.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/23/18 11:57 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.func_184191_r(EntityCreatureTameable.java:361)
	at com.lycanitesmobs.core.entity.EntityCreatureBase.canAttackEntity(EntityCreatureBase.java:2350)
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.canAttackEntity(EntityCreatureTameable.java:428)
	at com.lycanitesmobs.freshwatermobs.entity.EntityAbaia.func_70636_d(EntityAbaia.java:121)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.lycanitesmobs.core.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1370)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.func_184191_r(EntityCreatureTameable.java:361)
	at com.lycanitesmobs.core.entity.EntityCreatureBase.canAttackEntity(EntityCreatureBase.java:2350)
	at com.lycanitesmobs.core.entity.EntityCreatureTameable.canAttackEntity(EntityCreatureTameable.java:428)
	at com.lycanitesmobs.freshwatermobs.entity.EntityAbaia.func_70636_d(EntityAbaia.java:121)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.lycanitesmobs.core.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1370)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: freshwatermobs:abaia (com.lycanitesmobs.freshwatermobs.entity.EntityAbaia)
	Entity ID: 6235
	Entity Name: Kovak's Abaia
	Entity's Exact location: -15.55, 71.00, 695.05
	Entity's Block location: World: (-16,71,695), Chunk: (at 0,4,7 in -1,43; contains blocks -16,0,688 to -1,255,703), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kovak'/529, l='MpServer', x=-15.55, y=70.00, z=695.05]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (256,64,252), Chunk: (at 0,4,12 in 16,15; contains blocks 256,0,240 to 271,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 52429185 game time, 5702807 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityPlayerSP['Kovak'/529, l='MpServer', x=-15.55, y=70.00, z=695.05], EntitySilex['Silex'/5637, l='MpServer', x=-44.18, y=61.92, z=743.39], EntityCitizen['Aidan U. Gray'/806, l='MpServer', x=499.51, y=68.00, z=524.43], EntityChupacabra['Chupacabra'/5660, l='MpServer', x=-63.02, y=56.00, z=727.76], EntityBat['Bat'/5674, l='MpServer', x=16.44, y=16.63, z=706.27], EntityCitizen['Jeremiah G. Barber'/732, l='MpServer', x=480.97, y=65.00, z=576.68], EntityCitizen['Harper E. Courtenay'/797, l='MpServer', x=470.50, y=67.00, z=514.42], EntitySquid['Squid'/5680, l='MpServer', x=37.40, y=62.41, z=648.60], EntitySquid['Squid'/5681, l='MpServer', x=41.73, y=60.26, z=646.16], EntitySutiramu['Sutiramu'/6193, l='MpServer', x=-13.56, y=70.00, z=796.44], EntityCryptZombie['Crypt Zombie'/6194, l='MpServer', x=45.50, y=72.00, z=791.50], EntityBat['Bat'/6213, l='MpServer', x=-23.37, y=16.94, z=703.30], EntityCitizen['Guewen L. Askew'/805, l='MpServer', x=470.50, y=70.56, z=549.50], EntityKobold['Kobold'/4697, l='MpServer', x=101.33, y=27.00, z=755.45], EntityPortal['entity.summoningportal.name'/6233, l='MpServer', x=-15.52, y=70.00, z=695.07], EntityAbaia['Kovak's Abaia'/6235, l='MpServer', x=-15.55, y=71.00, z=695.05], EntityAbaia['Kovak's Abaia'/6236, l='MpServer', x=-15.55, y=71.00, z=695.05], EntityCitizen['Edith B. Alban'/658, l='MpServer', x=378.48, y=32.00, z=455.36], EntityChupacabra['Chupacabra'/5760, l='MpServer', x=-70.72, y=51.00, z=698.72], EntityChupacabra['Chupacabra'/5761, l='MpServer', x=-76.13, y=51.00, z=704.54], EntityChupacabra['Chupacabra'/5762, l='MpServer', x=-70.48, y=48.44, z=721.48], EntityCitizen['Matthew C. Goodwin'/804, l='MpServer', x=470.50, y=70.56, z=548.50], EntityChupacabra['Chupacabra'/4782, l='MpServer', x=71.36, y=16.25, z=663.46], EntityChupacabra['Chupacabra'/4785, l='MpServer', x=86.35, y=19.00, z=719.22], EntityKobold['Kobold'/4787, l='MpServer', x=83.51, y=25.84, z=740.37], EntityKobold['Kobold'/4788, l='MpServer', x=93.21, y=27.00, z=755.30], EntityKobold['Kobold'/4789, l='MpServer', x=84.99, y=25.00, z=776.48], EntityKobold['Baby Kobold'/4805, l='MpServer', x=102.87, y=25.00, z=786.13], EntityChicken['Chicken'/5837, l='MpServer', x=-80.11, y=86.00, z=767.50], EntityChupacabra['Violet Chupacabra'/4847, l='MpServer', x=64.30, y=30.00, z=667.44], EntityKobold['Ashen Kobold'/4848, l='MpServer', x=66.77, y=30.00, z=674.77], EntityKobold['Kobold'/4849, l='MpServer', x=74.79, y=21.00, z=688.48], EntityJoust['Joust'/5877, l='MpServer', x=-48.50, y=68.00, z=803.56], EntityKobold['Kobold'/4854, l='MpServer', x=63.22, y=29.00, z=740.22], EntityCitizen['Noah L. Attilburgh'/664, l='MpServer', x=377.50, y=86.00, z=544.33], EntityChupacabra['Chupacabra'/5419, l='MpServer', x=44.46, y=54.00, z=627.46], EntityChupacabra['Chupacabra'/5420, l='MpServer', x=48.57, y=52.88, z=630.27], EntityChupacabra['Chupacabra'/5421, l='MpServer', x=47.84, y=52.00, z=624.76], EntityChupacabra['Chupacabra'/5422, l='MpServer', x=33.52, y=43.00, z=654.52], EntityItem['item.tile.sand.default'/5455, l='MpServer', x=30.37, y=66.00, z=700.10], EntityItem['item.tile.sand.default'/5456, l='MpServer', x=29.95, y=67.00, z=699.13], EntityMinecartChest['Minecart with Chest'/5457, l='MpServer', x=21.50, y=26.00, z=719.11], EntityItem['item.item.seeds'/5458, l='MpServer', x=20.88, y=72.00, z=710.88], EntityItem['item.tile.sand.default'/5459, l='MpServer', x=26.76, y=73.00, z=713.59], EntityItem['item.tile.sand.default'/5460, l='MpServer', x=26.13, y=75.00, z=719.88], EntityChupacabra['Chupacabra'/5981, l='MpServer', x=-107.23, y=55.00, z=577.50], EntityBat['Bat'/6003, l='MpServer', x=45.54, y=18.10, z=638.25], EntityChupacabra['Chupacabra'/6005, l='MpServer', x=-124.14, y=58.00, z=767.74], EntitySilex['Silex'/6010, l='MpServer', x=-125.59, y=62.11, z=629.15], EntityCitizen['Ryan S. Archer'/816, l='MpServer', x=485.16, y=66.00, z=559.56], EntityChupacabra['Chupacabra'/4486, l='MpServer', x=102.52, y=65.00, z=609.73], EntityChupacabra['Chupacabra'/5510, l='MpServer', x=1.50, y=36.00, z=589.79], EntityChupacabra['Chupacabra'/5511, l='MpServer', x=5.41, y=51.00, z=637.36], EntityChupacabra['Chupacabra'/5512, l='MpServer', x=0.49, y=52.00, z=628.68], EntityChupacabra['Verdant Chupacabra'/5513, l='MpServer', x=4.49, y=46.00, z=688.48], EntityChupacabra['Chupacabra'/5514, l='MpServer', x=15.35, y=47.00, z=691.12], EntityChupacabra['Chupacabra'/5515, l='MpServer', x=14.56, y=47.00, z=696.35], EntityChupacabra['Chupacabra'/5516, l='MpServer', x=5.82, y=23.00, z=710.57], EntityBat['Bat'/6043, l='MpServer', x=32.47, y=27.05, z=696.36], EntityChupacabra['Chupacabra'/5022, l='MpServer', x=58.40, y=30.00, z=668.60], EntityChupacabra['Chupacabra'/5023, l='MpServer', x=60.54, y=31.00, z=668.54], EntityChupacabra['Chupacabra'/5025, l='MpServer', x=60.63, y=29.00, z=737.43], EntityBat['Bat'/6049, l='MpServer', x=64.25, y=20.00, z=733.66], EntityCitizen['Daniela E. Goldwell'/718, l='MpServer', x=430.11, y=66.00, z=466.50], EntityChupacabra['Chupacabra'/5545, l='MpServer', x=-2.49, y=52.00, z=654.23], EntityMinecartChest['Minecart with Chest'/5546, l='MpServer', x=-9.50, y=23.06, z=703.50], EntityChupacabra['Chupacabra'/5547, l='MpServer', x=-0.67, y=24.00, z=703.92], EntityJoust['Joust'/5548, l='MpServer', x=-0.50, y=68.00, z=759.56], EntityDjinn['Djinn'/6065, l='MpServer', x=66.46, y=128.00, z=735.46], EntityDjinn['Djinn'/6066, l='MpServer', x=7.45, y=131.45, z=660.59], EntityDjinn['Djinn'/6067, l='MpServer', x=70.68, y=117.03, z=739.55], EntityDjinn['Djinn'/6068, l='MpServer', x=65.47, y=129.00, z=642.47], EntityBeholder['Beholder'/6069, l='MpServer', x=-29.49, y=87.05, z=764.38], EntityCitizen['Samuel V. Barstaple'/734, l='MpServer', x=428.15, y=76.17, z=527.30], EntityRoc['Roc'/6070, l='MpServer', x=46.91, y=74.05, z=751.11], EntityRoc['Roc'/6071, l='MpServer', x=-55.02, y=63.31, z=742.97], EntityMorock['Morock'/6072, l='MpServer', x=-35.79, y=69.06, z=663.42], EntityRoc['Roc'/6073, l='MpServer', x=-28.22, y=73.02, z=640.52], EntityRoc['Roc'/6074, l='MpServer', x=21.11, y=69.91, z=580.23], EntityBeholder['Beholder'/6076, l='MpServer', x=38.88, y=109.91, z=742.30], EntityRoc['Roc'/6077, l='MpServer', x=-77.52, y=73.31, z=721.81], EntityChupacabra['Chupacabra'/5578, l='MpServer', x=-2.11, y=41.00, z=573.85], EntityBat['Bat'/6094, l='MpServer', x=-20.27, y=39.68, z=639.27], EntityChupacabra['Chupacabra'/5599, l='MpServer', x=-25.38, y=39.00, z=643.50], EntityChupacabra['Chupacabra'/5600, l='MpServer', x=-25.11, y=55.00, z=654.85], EntityChupacabra['Verdant Chupacabra'/5601, l='MpServer', x=-31.37, y=37.00, z=654.50], EntityBat['Bat'/6124, l='MpServer', x=-13.48, y=31.61, z=694.69], EntityBat['Bat'/6125, l='MpServer', x=-14.42, y=33.16, z=708.78], EntitySquid['Squid'/5613, l='MpServer', x=39.54, y=62.29, z=647.27], EntityBat['Bat'/6127, l='MpServer', x=-9.94, y=31.36, z=691.66], EntitySquid['Squid'/5615, l='MpServer', x=45.86, y=59.00, z=648.02], EntitySquid['Squid'/5616, l='MpServer', x=37.40, y=60.00, z=641.40], EntityBat['Bat'/6130, l='MpServer', x=-8.11, y=30.00, z=690.87]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Lycanite** [comment]
That's a weird one, so was it a pet attacking a wild Abaia, and single or multiplayer?

**Comment by Lycanite** [comment]
Perhaps getMinecraftServer() is the one returning null in a weird case, will have to throw in some null checks I guess.

**Comment by Kovak** [comment]
It was in multiplayer, it was just at the outset of summoning an Abaia. Server didn't crash, only client.

GetMinecraftServer seems to be dicorated with @Nullable.

**Comment by Lycanite** [comment]
Ooooh I see, that makes sense, I'll have to add a client side check for pvp, must be the Abaia's particle effect. The Zephyr will likely trigger the same crash too.

**Comment by Lycanite** [comment]
Fixed in 1.19.6.1.
