### ISSUE TITLE
[Spawning] Vanilla Crash On getNearestStructurePos With No Structure WorldGen

### ISSUE THREAD

**Issue by Nullga** [Lycanite/LycanitesMobs#414]
Crashes when playing in a world created with options for no structure generation.

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_180513_a(ChunkGeneratorOverworld.java:569)
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:305)
	at com.lycanitesmobs.core.spawner.location.StructureSpawnLocation.getSpawnPositions(StructureSpawnLocation.java:42)
	at com.lycanitesmobs.core.spawner.Spawner.getSpawnPos(Spawner.java:538)
	at com.lycanitesmobs.core.spawner.Spawner.doSpawn(Spawner.java:391)
	at com.lycanitesmobs.core.spawner.Spawner.trigger(Spawner.java:333)
	at com.lycanitesmobs.core.spawner.trigger.SpawnTrigger.trigger(SpawnTrigger.java:128)
	at com.lycanitesmobs.core.spawner.trigger.WorldSpawnTrigger.onTick(WorldSpawnTrigger.java:71)
	at com.lycanitesmobs.core.spawner.SpawnerEventListener.onWorldUpdate(SpawnerEventListener.java:194)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_843_SpawnerEventListener_onWorldUpdate_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Lycanite** [comment]
Ah easy enough to fix but annoying, it's actually a crash on vanillas side, it should really return null or an empty list of no structures rather than just crashing, either way I can patch it up on my end lol.

**Comment by Lycanite** [comment]
I'm curious, does an Eye of Ender also trigger this crash?

**Comment by Lycanite** [comment]
https://github.com/Lycanite/LycanitesMobs/commit/ac1a79881622e68cb145c5e37ea1b28987f5d28a
Got a fix ready for the next update. :)
