### ISSUE TITLE
Crash upon world load

### ISSUE THREAD

**Issue by Mewtwoy** [Lycanite/LycanitesMobs#79]
JSON error, cannot load any world

Description: Ticking player

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at lycanite.lycanitesmobs.api.pets.DonationFamiliars.readFromJSON(DonationFamiliars.java:61)
	at lycanite.lycanitesmobs.api.pets.DonationFamiliars.getFamiliarsForPlayer(DonationFamiliars.java:93)
	at lycanite.lycanitesmobs.ExtendedPlayer.onUpdate(ExtendedPlayer.java:136)
	at lycanite.lycanitesmobs.EventListener.onEntityUpdate(EventListener.java:137)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_272_EventListener_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 22 more

**Comment by Lycanite** [comment]
Oops, it might be related to the domain name change of the mod website,
does the crash still occur now?

**Comment by Lycanite** [comment]
I'll apply a fix in the latest updateso that it will ignore the JSON all together if it is malformed.

**Comment by Lycanite** [comment]
Shouldn't happen in the upcoming 1.11.0.0.
